"""Compatibility exports for factory metrics reporting helpers."""

from __future__ import annotations

from .archives import (
    _events_with_default_issue,
    _finished_issue_from_ledger_path,
    _finished_issue_ledger_label,
    _finished_issues_root,
    _iter_finished_issue_ledgers,
    _load_report_events,
)
from .readiness import (
    _event_text_values,
    _matched_markers,
    _numeric_metric,
    _positive_event,
    _readiness_context_markers,
    _readiness_evidence_entry,
    _readiness_gate_markers,
    _readiness_gate_result,
    _readiness_quality_markers,
    _readiness_report,
    _readiness_security_markers,
    _readiness_token_markers,
    _render_readiness_markdown,
)
from .report_markdown import (
    _format_counter_values,
    _format_ratio,
    _format_unknown_metric_counts,
    _render_report_markdown,
)
from .report_model import (
    _add_metrics,
    _empty_metric_totals,
    _finalize_model_comparison,
    _finalize_report_bucket,
    _issue_label,
    _issue_sort_key,
    _provider_model_label,
    _record_model_comparison,
    _record_report_counters,
    _report,
    _report_bucket,
)
from .summary import _summary

_REPORTING_HELPERS_REFERENCE = (
    _events_with_default_issue,
    _finished_issue_from_ledger_path,
    _finished_issue_ledger_label,
    _finished_issues_root,
    _iter_finished_issue_ledgers,
    _load_report_events,
    _event_text_values,
    _matched_markers,
    _numeric_metric,
    _positive_event,
    _readiness_context_markers,
    _readiness_evidence_entry,
    _readiness_gate_markers,
    _readiness_gate_result,
    _readiness_quality_markers,
    _readiness_report,
    _readiness_security_markers,
    _readiness_token_markers,
    _render_readiness_markdown,
    _format_counter_values,
    _format_ratio,
    _format_unknown_metric_counts,
    _render_report_markdown,
    _add_metrics,
    _empty_metric_totals,
    _finalize_model_comparison,
    _finalize_report_bucket,
    _issue_label,
    _issue_sort_key,
    _provider_model_label,
    _record_model_comparison,
    _record_report_counters,
    _report,
    _report_bucket,
    _summary,
)

__all__ = [
    "_events_with_default_issue",
    "_finished_issue_from_ledger_path",
    "_finished_issue_ledger_label",
    "_finished_issues_root",
    "_iter_finished_issue_ledgers",
    "_load_report_events",
    "_event_text_values",
    "_matched_markers",
    "_numeric_metric",
    "_positive_event",
    "_readiness_context_markers",
    "_readiness_evidence_entry",
    "_readiness_gate_markers",
    "_readiness_gate_result",
    "_readiness_quality_markers",
    "_readiness_report",
    "_readiness_security_markers",
    "_readiness_token_markers",
    "_render_readiness_markdown",
    "_format_counter_values",
    "_format_ratio",
    "_format_unknown_metric_counts",
    "_render_report_markdown",
    "_add_metrics",
    "_empty_metric_totals",
    "_finalize_model_comparison",
    "_finalize_report_bucket",
    "_issue_label",
    "_issue_sort_key",
    "_provider_model_label",
    "_record_model_comparison",
    "_record_report_counters",
    "_report",
    "_report_bucket",
    "_summary",
]
