#!/usr/bin/env python3
# ruff: noqa: E402, E501, F401, I001
"""Compatibility wrapper for local software-factory metrics."""

from __future__ import annotations

import sys
from pathlib import Path

_SCRIPT_DIR = Path(__file__).resolve().parent
if str(_SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(_SCRIPT_DIR))

from factory_metrics_modules.cli import (  # noqa: F401
    _add_common_output_args as _add_common_output_args,
    _append_command as _append_command,
    _context_scorecard_command as _context_scorecard_command,
    _context_scorecard_report_command as _context_scorecard_report_command,
    _context_scorecard_validate_command as _context_scorecard_validate_command,
    _readiness_command as _readiness_command,
    _report_command as _report_command,
    _summary_command as _summary_command,
    _validate_command as _validate_command,
    build_parser as build_parser,
    main as main,
)
from factory_metrics_modules.common import (  # noqa: F401
    FactoryMetricsError as FactoryMetricsError,
    _contains_control_character as _contains_control_character,
    _contains_secret_like as _contains_secret_like,
    _counter_dict as _counter_dict,
    _ensure_no_symlink_components as _ensure_no_symlink_components,
    _lexical_absolute as _lexical_absolute,
    _markdown_cell as _markdown_cell,
    _print_payload as _print_payload,
    _redact_text as _redact_text,
    _repo_root as _repo_root,
    _resolve_context_file as _resolve_context_file,
    _safe_context_scorecard_input_path as _safe_context_scorecard_input_path,
    _safe_factory_metrics_path as _safe_factory_metrics_path,
    _safe_ledger_path as _safe_ledger_path,
    _safe_report_label as _safe_report_label,
    _safe_report_path as _safe_report_path,
    _unknown_safe_report_label as _unknown_safe_report_label,
    _validate_note as _validate_note,
    _write_report_output as _write_report_output,
)
from factory_metrics_modules.context_scorecard import (  # noqa: F401
    _best_context_trial as _best_context_trial,
    _compare_context_tool_trial as _compare_context_tool_trial,
    _compare_metric as _compare_metric,
    _context_scorecard_report as _context_scorecard_report,
    _context_tool_missing_metrics as _context_tool_missing_metrics,
    _context_tool_report_entry as _context_tool_report_entry,
    _context_tool_setup_entry as _context_tool_setup_entry,
    _context_tool_source_counts as _context_tool_source_counts,
    _context_trial_improvement_count as _context_trial_improvement_count,
    _is_number as _is_number,
    _load_context_scorecard as _load_context_scorecard,
    _render_context_scorecard_markdown as _render_context_scorecard_markdown,
    _scorecard_metric_value as _scorecard_metric_value,
    _validate_context_scorecard_evaluation as _validate_context_scorecard_evaluation,
    _validate_context_scorecard_evidence as _validate_context_scorecard_evidence,
    _validate_context_scorecard_metrics as _validate_context_scorecard_metrics,
    _validate_context_scorecard_setup as _validate_context_scorecard_setup,
    _validate_context_scorecard_trial as _validate_context_scorecard_trial,
    _validate_context_tool_scorecard as _validate_context_tool_scorecard,
    _validate_scorecard_string_list as _validate_scorecard_string_list,
    _validate_scorecard_text as _validate_scorecard_text,
)
from factory_metrics_modules.events import (  # noqa: F401
    _append_jsonl as _append_jsonl,
    _context_metrics as _context_metrics,
    _event_from_args as _event_from_args,
    _load_events as _load_events,
    _validate_event as _validate_event,
    _validate_non_negative as _validate_non_negative,
)
from factory_metrics_modules.reporting import (  # noqa: F401
    _add_metrics as _add_metrics,
    _empty_metric_totals as _empty_metric_totals,
    _event_text_values as _event_text_values,
    _events_with_default_issue as _events_with_default_issue,
    _finalize_model_comparison as _finalize_model_comparison,
    _finalize_report_bucket as _finalize_report_bucket,
    _finished_issue_from_ledger_path as _finished_issue_from_ledger_path,
    _finished_issue_ledger_label as _finished_issue_ledger_label,
    _finished_issues_root as _finished_issues_root,
    _format_counter_values as _format_counter_values,
    _format_ratio as _format_ratio,
    _format_unknown_metric_counts as _format_unknown_metric_counts,
    _issue_label as _issue_label,
    _issue_sort_key as _issue_sort_key,
    _iter_finished_issue_ledgers as _iter_finished_issue_ledgers,
    _load_report_events as _load_report_events,
    _matched_markers as _matched_markers,
    _numeric_metric as _numeric_metric,
    _positive_event as _positive_event,
    _provider_model_label as _provider_model_label,
    _readiness_context_markers as _readiness_context_markers,
    _readiness_evidence_entry as _readiness_evidence_entry,
    _readiness_gate_markers as _readiness_gate_markers,
    _readiness_gate_result as _readiness_gate_result,
    _readiness_quality_markers as _readiness_quality_markers,
    _readiness_report as _readiness_report,
    _readiness_security_markers as _readiness_security_markers,
    _readiness_token_markers as _readiness_token_markers,
    _record_model_comparison as _record_model_comparison,
    _record_report_counters as _record_report_counters,
    _render_readiness_markdown as _render_readiness_markdown,
    _render_report_markdown as _render_report_markdown,
    _report as _report,
    _report_bucket as _report_bucket,
    _summary as _summary,
)
from factory_metrics_modules.schema import (  # noqa: F401
    ALLOWED_EVENT_KEYS as ALLOWED_EVENT_KEYS,
    ALLOWED_METRIC_KEYS as ALLOWED_METRIC_KEYS,
    ALL_METRICS as ALL_METRICS,
    CONTEXT_SCORECARD_ALLOWED_KEYS as CONTEXT_SCORECARD_ALLOWED_KEYS,
    CONTEXT_SCORECARD_ALLOWED_SOURCE_TYPES as CONTEXT_SCORECARD_ALLOWED_SOURCE_TYPES,
    CONTEXT_SCORECARD_BASELINE_KEYS as CONTEXT_SCORECARD_BASELINE_KEYS,
    CONTEXT_SCORECARD_EVALUATION_KEYS as CONTEXT_SCORECARD_EVALUATION_KEYS,
    CONTEXT_SCORECARD_EVIDENCE_KEYS as CONTEXT_SCORECARD_EVIDENCE_KEYS,
    CONTEXT_SCORECARD_FORBIDDEN_SOURCE_TYPES as CONTEXT_SCORECARD_FORBIDDEN_SOURCE_TYPES,
    CONTEXT_SCORECARD_HIGHER_IS_BETTER as CONTEXT_SCORECARD_HIGHER_IS_BETTER,
    CONTEXT_SCORECARD_INTEGER_METRICS as CONTEXT_SCORECARD_INTEGER_METRICS,
    CONTEXT_SCORECARD_PROOF_STATUSES as CONTEXT_SCORECARD_PROOF_STATUSES,
    CONTEXT_SCORECARD_RATE_METRICS as CONTEXT_SCORECARD_RATE_METRICS,
    CONTEXT_SCORECARD_RECOMMENDATIONS as CONTEXT_SCORECARD_RECOMMENDATIONS,
    CONTEXT_SCORECARD_REPORT_SCHEMA_VERSION as CONTEXT_SCORECARD_REPORT_SCHEMA_VERSION,
    CONTEXT_SCORECARD_REQUIRED_BASELINE_COMPONENTS as CONTEXT_SCORECARD_REQUIRED_BASELINE_COMPONENTS,
    CONTEXT_SCORECARD_REQUIRED_METRICS as CONTEXT_SCORECARD_REQUIRED_METRICS,
    CONTEXT_SCORECARD_SCHEMA_VERSION as CONTEXT_SCORECARD_SCHEMA_VERSION,
    CONTEXT_SCORECARD_SETUP_KEYS as CONTEXT_SCORECARD_SETUP_KEYS,
    CONTEXT_SCORECARD_SETUP_STATUSES as CONTEXT_SCORECARD_SETUP_STATUSES,
    CONTEXT_SCORECARD_TRIAL_KEYS as CONTEXT_SCORECARD_TRIAL_KEYS,
    CONTROL_CHARACTER_PATTERN as CONTROL_CHARACTER_PATTERN,
    DECISIONS as DECISIONS,
    DEFAULT_LEDGER as DEFAULT_LEDGER,
    EVENT_SCHEMA_VERSION as EVENT_SCHEMA_VERSION,
    EVENT_TYPES as EVENT_TYPES,
    FINISHED_ISSUES_DIR as FINISHED_ISSUES_DIR,
    FINISHED_ISSUE_DIR_RE as FINISHED_ISSUE_DIR_RE,
    FLOAT_METRICS as FLOAT_METRICS,
    INTEGER_METRICS as INTEGER_METRICS,
    NO_PROVIDER_MARKERS as NO_PROVIDER_MARKERS,
    NOTE_FORBIDDEN_PATTERN as NOTE_FORBIDDEN_PATTERN,
    NOTE_MAX_LENGTH as NOTE_MAX_LENGTH,
    OUTCOMES as OUTCOMES,
    QUALITY_MARKERS as QUALITY_MARKERS,
    READINESS_GATES as READINESS_GATES,
    READINESS_MISSING_MESSAGES as READINESS_MISSING_MESSAGES,
    READINESS_SCHEMA_VERSION as READINESS_SCHEMA_VERSION,
    REPORT_SCHEMA_VERSION as REPORT_SCHEMA_VERSION,
    ROLES as ROLES,
    SECRET_REDACTIONS as SECRET_REDACTIONS,
    SECURITY_MARKERS as SECURITY_MARKERS,
    SUMMARY_SCHEMA_VERSION as SUMMARY_SCHEMA_VERSION,
    TEXT_FIELDS as TEXT_FIELDS,
    UTC_TZ as UTC_TZ,
)

if __name__ == "__main__":
    raise SystemExit(main())
